### ISSUE TITLE
Folder name clash

### ISSUE THREAD

**Issue by janfreyberg** [rb643/resting_state_eeg#2]
I think I accidentally caused a clash between some folder names, calling it data rather than Data

D:

**Comment by rb643** [comment]
Shouldn't be a big issue though :)

**Comment by rb643** [comment]
The other data folder doesn't seem to be synching with mine anyway :) 

Also, doesn't the init file need to go in the 'top' directory?

**Comment by janfreyberg** [comment]
Yeah I only have one folder!

And the `__init__` file can be in any directory, it's just what is run when you call `import foldername`

**Comment by janfreyberg** [comment]
I'll push what I worked on yesterday in a sec

**Comment by janfreyberg** [comment]
I think I fixed this, your folder should now also be called data, not Data.

Makes life easier ;)

**Comment by janfreyberg** [comment]
@rb643 I fixed this on the github repo, but to fix this on your local machine you might have to delete the repository and clone it again... then we won't have to change `data` to `Data` all the time!
