### ISSUE TITLE
running graph analysis

### ISSUE THREAD

**Issue by rb643** [rb643/resting_state_eeg#9]
Ran into troubles trying to install igraph for python so have converted back to doing it in R :) Started with some examples, but it should be quit easy to start adding graph metrics to the same loop.

**Comment by janfreyberg** [comment]
Sounds good! Although it could be nice to do it in a jupyter notebook with an R kernel rather than in `Rmd`, just so you can edit both notebooks at the same time.

**Comment by rb643** [comment]
done!
